#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ ${#@} -eq 4 ]
then
    scp -o StrictHostKeyChecking=False -i "$4" "$1" "$3@$2":~
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
