#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo mkdir /etc/nginx/redirect_me
sudo touch /etc/nginx/redirect_me/redirects.conf
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
