#!/usr/bin/env bash
# Bash script that configure nginx and add header
apt update -y
apt install -y nginx
sed -i "/listen \[::\]:80 default_server;/a\    add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
service nginx restart
