#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
apt -y update && upgrade -y;
apt install -y haproxy;
echo "frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 3627-web-01	34.139.172.50:80 check
    server 3627-web-02	35.243.158.214:80 check" >> /etc/haproxy/haproxy.cfg;
service haproxy restart;
