#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process
if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo "$!" >> /var/run/myscript.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    kill $(cat /var/run/myscript.pid)
    sudo rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    kill $(cat /var/run/myscript.pid)
    sudo rm -f /var/run/my_process.pid
    ./manage_my_process &
    sudo touch /var/run/myscript.pid
    pgrep -f ./manage_my_process >> /var/run/myscript.pid
    echo "manage_my_process started"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
