#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 fizzbuzz
for ((i = 1; i <= 100; i++)); do
    if ((i % 15 == 0)); then
        echo "FizzBuzz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    else
        echo "$i"
    fi
done
