#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hour=0
min=0
while ((hour <= 12))
do
    while ((min < 60))
    do
        if [ $min == 0 ]
        then
            echo "Hour: $hour"
        else
            echo "$min"
        fi
        ((min++))
    done
    min=0
    ((hour++))
done
